# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Unit and UI Tests"
  lane :tests do
    scan(
      project: "sport-shooting.xcodeproj",
      scheme: "sport-shooting",
      clean: false,
      devices: ["iPhone 16", "iPhone 16 Pro"],
      fail_build: true,
      force_quit_simulator: true
    )
  end
end
