name: iOS Tests with Fastlane

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    name: Run Tests using Fastlane
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode 15
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Install Bundler and Fastlane
        run: |
          gem install bundler
          bundle install
          gem install fastlane

      - name: Run Tests with Fastlane
        run: fastlane tests
